name: buildx

on:
  pull_request:
    branches: mon
  push:
    branches: mon

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Prepare
        id: prepare
        run: |
          DOCKER_PLATFORMS=linux/amd64,linux/arm64
          SOURCE_BRANCH=mon
          SOURCE_COMMIT=
          COMMIT_MSG=
          DOCKER_REPO=betsyweilin/get-started
          DOCKERFILE_PATH=./Dockerfile
          DOCKER_TAG=lin
          IMAGE_NAME=${DOCKER_REPO}:${DOCKER_TAG}

          VERSION=edge

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          fi

          TAGS="--tag ${DOCKER_REPO}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS --tag ${DOCKER_REPO}:latest"
          fi

          echo ::set-output name=docker_image::${DOCKER_REPO}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=buildx_args::--platform ${DOCKER_PLATFORMS} \
            --build-arg VERSION=${VERSION} \
            --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \



      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: betsyweilin
          password: 88weilinlin
      -
        name: Docker Buildx (push)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform  linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag betsyweilin/get-started:test1 \
            --file ./Dockerfile ./
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect betsyweilin/get-started:test
